### PR TITLE
gg_ttgg dpct conversion

### PR DESCRIPTION
**Pull request by tjburch**
Hi @lfield,
I noticed [PR  #64](https://github.com/madgraph5/madgraph4gpu/pull/64) wasn't yet merged. Here I've included the dpct conversion of the gg_ttgg directory. Thought it maybe made sense to merge into your branch then have the two go in as a set rather than create an independent PR in the upstream. Let me know your thoughts.

The command used was the same as the one you did:

```
dpct  --extra-arg="-std=c++11" --extra-arg="-D __CUDACC__" --extra-arg "-I ../../../tools/" --comments  --usm-level=none  --in-root . SubProcesses/P1_Sigma_sm_gg_ttxgg/*.cu src/*.cu --out-root dpct-output
```

Then I did a check of files and copied them back into the associated cuda directories.

### CODE REVIEW

**Comment by lfield** [comment]
I don't think this is the correct approach. I finished my SYLC version today but need to clean the code a little before I push. I will send you an email tomorrow with my thoughts on how to proceed.

**Comment by tjburch** [comment]
As in, using DPCT at all is not the correct approach?

**Comment by lfield** [comment]
No, the branch merge.

**Comment by tjburch** [comment]
Ah that works - will wait to hear via email. Thanks 👍

**Comment by lfield** [comment]
Will close this. You should do a PR against the upstream repository.

**Pull request closed without merging**
